<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>MermaidIsland</AssemblyName>
    <RootNamespace>MermaidIsland</RootNamespace>
    <Version>0.0.1</Version>
    <TargetFramework>net6.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.0.0" />
  </ItemGroup>
</Project>
